### ISSUE TITLE
Build fails. do i have to install anything?

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#75]
Build fails.
do i have to install anything?
```

> build:embed
> parcel build src/embed.ts

Error: Cannot find module './lib/stringify'
Require stack:
- /mnt/c/foo/bar/Klecks/node_modules/braces/index.js
- /mnt/c/foo/bar/Klecks/node_modules/micromatch/index.js
- /mnt/c/foo/bar/Klecks/node_modules/@parcel/watcher/index.js
- /mnt/c/foo/bar/Klecks/node_modules/@parcel/fs/lib/index.js
- /mnt/c/foo/bar/Klecks/node_modules/parcel/lib/cli.js
- /mnt/c/foo/bar/Klecks/node_modules/parcel/lib/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/mnt/c/foo/bar/Klecks/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/mnt/c/foo/bar/Klecks/node_modules/braces/index.js:3:19)
    at Module._compile (/mnt/c/foo/bar/Klecks/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/foo/bar/Klecks/node_modules/braces/index.js',
    '/mnt/c/foo/bar/Klecks/node_modules/micromatch/index.js',
    '/mnt/c/foo/bar/Klecks/node_modules/@parcel/watcher/index.js',
    '/mnt/c/foo/bar/Klecks/node_modules/@parcel/fs/lib/index.js',
    '/mnt/c/foo/bar/Klecks/node_modules/parcel/lib/cli.js',
    '/mnt/c/foo/bar/Klecks/node_modules/parcel/lib/bin.js'
  ]
}

```

**Comment by satopian** [comment]
```
	"braces": "^3.0.2",
	"micromatch": "^4.0.4",
	"normalize-path": "^3.0.0",
	"picomatch": "^2.3.0",
	"regex-not": "^1.0.2",
	"snapdragon": "^0.8.2",
	"to-regex": "^3.0.2"

```
When I added what I thought I needed to package.json, I was able to build.
However, I'm not sure if what I specified was correct.
It would be very helpful if you could fix the package.json.

**Comment by satopian** [comment]
@bitbof thank you.
solved.
It's my mistake.
